language: rust

rust: stable

script: cargo build

jobs:
  include:
    - stage: "test"
      script: "cargo test"
    - rust: "nightly"
      allow_failures: true
    - rust: "beta"
      allow_failures: true

    - stage: "Github release"
      script: 
       - "cargo build --release"
       - "cd target/release && zip lsd-$(rustup show active-toolchain).zip lsd && cd ../.."
      if: "tag IS present"
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        file: "target/release/lsd-*.zip"
        file_glob: true
        # This may seem redundant. But this is necessary. See travis-ci/travis-ci#8289
        on:
          tags: true
